BEGIN;

CREATE TABLE IF NOT EXISTS players2 (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT NOT NULL UNIQUE ON CONFLICT REPLACE,
    elo     INTEGER NOT NULL DEFAULT(1000)
);

CREATE TABLE IF NOT EXISTS fights (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    ended   DATETIME NOT NULL,
    winner  INTEGER,
    one     INTEGER,
    two     INTEGER,
    FOREIGN KEY (one) REFERENCES players(id),
    FOREIGN KEY (two) REFERENCES players(id)
);

COMMIT;
